class Localization {
  static const Map<String, Map<String, String>> strings = {
    'en': {
      'login_title': 'Nenavi',
      'login_subtitle': 'Memory Care Companion',
      'email': 'Email',
      'password': 'Password',
      'sign_in': 'Sign In',
      'new_here': 'New here? ',
      'create_account': 'Create an account',
      'register_title': 'Create Account',
      'welcome_nenavi': 'Welcome to Nenavi',
      'fill_details': 'Fill in the details below to get started.',
      'name': 'Full Name',
      'age': 'Age',
      'role_question': 'I am a…',
      'patient': 'Patient',
      'caregiver': 'Caregiver',
      'caregiver_email': 'Caregiver\'s Email',
      'already_have_account': 'Already have an account? Sign in',
      'dashboard_title': 'My Dashboard',
      'sign_out': 'Sign out',
      'good_day': 'Good day!',
      'start_test': 'Start Today\'s Test',
      'test_in_progress': 'In progress…',
      'test_subtitle':
          'Takes about 10 minutes.\nDo it at the same time each day.',
      'score_history': 'Score History',
      'history_subtitle': 'See how you have been doing over time.',
      'view_scores': 'View My Scores',
      'last_score': 'Last Score',
      'language': 'Language',
      'time_remaining': 'Time Remaining',
    },
    'kn': {
      'login_title': 'ನೆನವಿ',
      'login_subtitle': 'ನೆನಪಿನ ಆರೈಕೆ ಸಂಗಾತಿ',
      'email': 'ಇಮೇಲ್ (Email)',
      'password': 'ಪಾಸ್‌ವರ್ಡ್ (Password)',
      'sign_in': 'ಲಾಗಿನ್ ಮಾಡಿ (Sign In)',
      'new_here': 'ಹೊಸಬರೇ? ',
      'create_account': 'ಖಾತೆ ರಚಿಸಿ (Create an account)',
      'register_title': 'ಖಾತೆ ರಚಿಸಿ',
      'welcome_nenavi': 'ನೆನವಿಗೆ ಸ್ವಾಗತ',
      'fill_details': 'ಪ್ರಾರಂಭಿಸಲು ಕೆಳಗಿನ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.',
      'name': 'ಪೂರ್ಣ ಹೆಸರು (Full Name)',
      'age': 'ವಯಸ್ಸು (Age)',
      'role_question': 'ನಾನು ಒಬ್ಬ…',
      'patient': 'ರೋಗಿ (Patient)',
      'caregiver': 'ಆರೈಕೆದಾರ (Caregiver)',
      'caregiver_email': 'ಆರೈಕೆದಾರರ ಇಮೇಲ್',
      'already_have_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ? ಲಾಗಿನ್ ಮಾಡಿ',
      'dashboard_title': 'ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'sign_out': 'ಸೈನ್ ಔಟ್ ಮಾಡಿ',
      'good_day': 'ಶುಭ ದಿನ!',
      'start_test': 'ಇಂದಿನ ಪರೀಕ್ಷೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ',
      'test_in_progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ…',
      'test_subtitle':
          'ಸುಮಾರು ೧೦ ನಿಮಿಷ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ.\nಪ್ರತಿದಿನ ಒಂದೇ ಸಮಯಕ್ಕೆ ಮಾಡಿ.',
      'score_history': 'ಸ್ಕೋರ್ ಇತಿಹಾಸ',
      'history_subtitle': 'ಕಾಲಾನಂತರದಲ್ಲಿ ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ನೋಡಿ.',
      'view_scores': 'ನನ್ನ ಸ್ಕೋರ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
      'last_score': 'ಕೊನೆಯ ಸ್ಕೋರ್',
      'language': 'ಭಾಷೆ (Language)',
      'time_remaining': 'ಉಳಿದ ಸಮಯ',
    },
    'tcy': {
      'login_title': 'ನೆನವಿ',
      'login_subtitle': 'ನೆಂಪುದ ಆರೈಕೆ ಸಂಗಾತಿ',
      'email': 'ಇಮೇಲ್ (Email)',
      'password': 'ಪಾಸ್‌ವರ್ಡ್ (Password)',
      'sign_in': 'ಲಾಗಿನ್ ಮಲ್ಪುಲೆ (Sign In)',
      'new_here': 'ಪೊಸಬೆರಾ? ',
      'create_account': 'ಖಾತೆ ಮಲ್ಪುಲೆ (Create an account)',
      'register_title': 'ಖಾತೆ ಮಲ್ಪುಲೆ',
      'welcome_nenavi': 'ನೆನವಿಗ್ ಸ್ವಾಗತ',
      'fill_details': 'ಸುರು ಮಲ್ಪೆರೆ ತಿರ್ತದ ವಿವರೊಲೆನ್ ಬರೆಲೆ.',
      'name': 'ಪೂರ್ಣ ಪುದರ್ (Full Name)',
      'age': 'ಪ್ರಾಯ (Age)',
      'role_question': 'ಯಾನ್ ಒರಿ…',
      'patient': 'ಸೀಕ್ ದಾಯೆ (Patient)',
      'caregiver': 'ಆರೈಕೆ ಮಲ್ಪುನಾಯೆ (Caregiver)',
      'caregiver_email': 'ಆರೈಕೆ ಮಲ್ಪುನಾಯನ ಇಮೇಲ್',
      'already_have_account': 'ದುಂಬೆ ಖಾತೆ ಉಂಡಾ? ಲಾಗಿನ್ ಮಲ್ಪುಲೆ',
      'dashboard_title': 'ಯನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'sign_out': 'ಸೈನ್ ಔಟ್ ಮಲ್ಪುಲೆ',
      'good_day': 'ಎಡ್ಡೆ ದಿನ!',
      'start_test': 'ಇನಿಯ ಪರೀಕ್ಷೆನ್ ಸುರು ಮಲ್ಪುಲೆ',
      'test_in_progress': 'ನಡತೊಂದುಂಡು…',
      'test_subtitle':
          'ಸುಮಾರ್ ೧೦ ನಿಮಿಷ ದೆತೊನುಂಡು.\nದಿನಾಲ ಒಂಜೇ ಪೊರ್ತುಗು ಮಲ್ಪುಲೆ.',
      'score_history': 'ಸ್ಕೋರ್ ಇತಿಹಾಸ',
      'history_subtitle': 'ಕಾಲ ಕರಿನಂಚನೆ ಈರೆನ ಪ್ರಗತಿನ್ ತೂಲೆ.',
      'view_scores': 'ಯನ್ನ ಸ್ಕೋರ್‌ಲೆನ್ ತೂಲೆ',
      'last_score': 'ಕಡೆತ ಸ್ಕೋರ್',
      'language': 'ಭಾಷೆ (Language)',
      'time_remaining': 'ಒರಿದಿನ ಪೊರ್ತು',
    },
  };

  static String get(String key, String language) {
    if (!strings.containsKey(language)) return strings['en']![key] ?? key;
    return strings[language]![key] ?? strings['en']![key] ?? key;
  }
}
